#!/usr/bin/env bash

user=$USER
# shared=//YANLL-WORK/d/
shared=//YANLL-WORK/d$
mountpoint=/d/
uid=`id -u`
gid=`id -g`

case $1 in
  -u )
    sudo umount $mountpoint
    ;;
  * )
    read -s -p "Enter Password for $user@microsoft.com: " pass
    echo ""
    sudo mount -t cifs -o user=$user,password=$pass,domain=fareast,uid=$uid,gid=$gid $shared $mountpoint
    ;;
esac

